# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/applicationset-specification/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echo-server-node-appset
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
  #   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  #   argocd.argoproj.io/compare-options: IgnoreExtraneous
  #   argocd.argoproj.io/refresh: "1m"
  #   argocd.argoproj.io/refresh-interval: "1m"
  #   argocd.argoproj.io/refresh-on-sync: "true"
  #   argocd.argoproj.io/refresh-on-commit: "true"
  #   argocd.argoproj.io/refresh-on-push: "true"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: core-nonprod
        ns: develop
        valuesFile: values-develop.yaml
        autoSync: true
        prune: true
        selfHeal: true
      - cluster: core-nonprod
        ns: staging
        valuesFile: values-staging.yaml
        autoSync: false
        prune: true
        selfHeal: false
      - cluster: core-nonprod
        ns: test1
        valuesFile: values-test1.yaml
        autoSync: false
        prune: true
        selfHeal: false
      - cluster: core-nonprod
        ns: test2
        valuesFile: values-test2.yaml
        autoSync: false
        prune: true
        selfHeal: false

  template: # used to generate Argo CD Application resources
    metadata:
      name: '{{.ns}}-echo-server-node'
      namespace: argocd
    spec:
      project: default
      # Source of the application manifests
      source:
        repoURL: https://github.com/VectorLearning/poc_echo_server_node.git
        targetRevision: HEAD
        path: ./src/helm/echo-server-node
        # Helm specific config
        helm:
          passCredentials: false
          releaseName: '{{.ns}}'
          valueFiles:
          - '{{.valuesFile}}'
      # Destination cluster and namespace to deploy the application
      destination:
        name: '{{.cluster}}'
        namespace: '{{.ns}}'
      
  templatePatch: |
    spec:
      # Sync policy
      syncPolicy:
        syncOptions:
        - CreateNamespace=false
        {{- if .autoSync }}
        automated: # enables auto-sync
          prune: {{ .prune }}
          selfHeal: {{ .selfHeal }}
        {{- else }}
        automated: null
        {{- end }}
